-- MySQL Script generated by MySQL Workbench
-- Tue May 26 11:45:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa` DEFAULT CHARACTER SET utf8 ;
USE `empresa` ;

-- -----------------------------------------------------
-- Table `empresa`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `nomeCargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nomeFuncionario` VARCHAR(50) NOT NULL,
  `id_Cargo` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_funcionario_cargo_idx` (`id_Cargo` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_cargo`
    FOREIGN KEY (`id_Cargo`)
    REFERENCES `empresa`.`cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`dependente` (
  `idDependente` INT NOT NULL AUTO_INCREMENT,
  `nomeDependente` VARCHAR(30) NOT NULL,
  `id_Funcionario` INT NOT NULL,
  PRIMARY KEY (`idDependente`),
  INDEX `fk_dependente_funcionario_idx` (`id_Funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_dependente_funcionario`
    FOREIGN KEY (`id_Funcionario`)
    REFERENCES `empresa`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(100) NOT NULL,
  `id_Funcionario` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_endereco_funcionario_idx` (`id_Funcionario` ASC) INVISIBLE,
  CONSTRAINT `fk_endereco_funcionario`
    FOREIGN KEY (`id_Funcionario`)
    REFERENCES `empresa`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `id_Funcionario` INT NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_telefone_funcionario_idx` (`id_Funcionario` ASC) INVISIBLE,
  CONSTRAINT `fk_telefone_funcionario`
    FOREIGN KEY (`id_Funcionario`)
    REFERENCES `empresa`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
